apiVersion: v2
name: local-chart-with-deps
description: Test case for reproducing helm dep build errors with unreachable repos
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: "4.10.0"
    repository: "https://kubernetes.github.oopsie/ingress-nginx"
